Repository minitap-ai/mobile-use, pull requests merged in 2025-09, with the labels that each got.

#45 Release 2.1.0
  README.md
  pyproject.toml
  uv.lock
Labels: documentation

#48 Release v2.2.0
  Dockerfile
  README.md
  docker-compose.yml
  minitap/mobile_use/main.py
  minitap/mobile_use/sdk/builders/agent_config_builder.py
  pyproject.toml
  slim.Dockerfile
  uv.lock
Labels: enhancement

#60 feat(ui-hierarchy): add comprehensive test suite and fix bounds calculation
  .github/workflows/feature.yml
  CONTRIBUTING.md
  minitap/mobile_use/agents/outputter/test_outputter.py
  minitap/mobile_use/tools/test_utils.py
  minitap/mobile_use/utils/test_ui_hierarchy.py
  minitap/mobile_use/utils/ui_hierarchy.py
  pyproject.toml
  uv.lock
Labels: bug, documentation, enhancement
