Repository minitap-ai/mobile-use, pull requests merged in 2025-08, with the labels that each got.

#4 docs: added troubleshooting section to quickstart section
  README.md
  mobile-use.ps1
  mobile-use.sh
Labels: documentation, enhancement

#9 feat: add feature-request issue template
  .github/ISSUE_TEMPLATE/feature-request-🚀.md
Labels: documentation

#18 SDK for easily integrating mobile-use in python projects
  src/mobile_use/agents/cortex/cortex.py
  src/mobile_use/agents/executor/executor.md
  src/mobile_use/agents/executor/executor.py
  src/mobile_use/agents/hopper/hopper.py
  src/mobile_use/agents/orchestrator/orchestrator.py
  src/mobile_use/agents/outputter/outputter.py
  src/mobile_use/agents/outputter/test_outputter.py
  src/mobile_use/agents/planner/planner.py
  src/mobile_use/config.py
  src/mobile_use/context.py
  src/mobile_use/controllers/platform_specific_commands_controller.py
  src/mobile_use/llm_config_context.py
  src/mobile_use/main.py
  src/mobile_use/sdk/__init__.py
  src/mobile_use/sdk/agent.py
  src/mobile_use/sdk/builders/__init__.py
  src/mobile_use/sdk/builders/agent_config_builder.py
  src/mobile_use/sdk/builders/index.py
  src/mobile_use/sdk/builders/task_request_builder.py
  src/mobile_use/sdk/constants.py
  src/mobile_use/sdk/examples/README.md
  src/mobile_use/sdk/examples/__init__.py
  src/mobile_use/sdk/examples/simple_photo_organizer.py
  src/mobile_use/sdk/examples/smart_notification_assistant.py
  src/mobile_use/sdk/types/__init__.py
  src/mobile_use/sdk/types/agent.py
  src/mobile_use/sdk/types/exceptions.py
  src/mobile_use/sdk/types/task.py
  src/mobile_use/sdk/utils.py
  src/mobile_use/servers/device_hardware_bridge.py
  src/mobile_use/servers/start_servers.py
  src/mobile_use/services/llm.py
  src/mobile_use/tools/mobile/list_packages.py
  src/mobile_use/utils/cli_helpers.py
  src/mobile_use/utils/recorder.py
Labels: documentation, enhancement

#23 All LLMs are configurable - OpenAI API key no longer required
  README.md
  llm-config.defaults.jsonc
  src/mobile_use/agents/cortex/cortex.py
  src/mobile_use/agents/executor/executor.py
  src/mobile_use/agents/hopper/hopper.py
  src/mobile_use/agents/orchestrator/orchestrator.py
  src/mobile_use/agents/outputter/outputter.py
  src/mobile_use/agents/planner/planner.py
  src/mobile_use/config.py
  src/mobile_use/sdk/builders/agent_config_builder.py
  src/mobile_use/sdk/examples/smart_notification_assistant.py
  src/mobile_use/services/llm.py
Labels: documentation, enhancement

#25 chore(docs): correct misspelling of "completion"
  README.md
  doc/benchmark.jpg
  doc/benchmark.png
Labels: documentation

#26 PyPI package deployment + DockerHub image deployment on Releases
  .github/workflows/docker.yml
  .github/workflows/pypi.yml
  .github/workflows/ruff.yml
  Dockerfile
  docker-compose.yml
  slim.Dockerfile
Labels: enhancement

#27 ci: refactored workflow so the deployment does not occur on release but on tags
  .github/workflows/deployment.yml
  .github/workflows/docker.yml
  .github/workflows/feature.yml
  .github/workflows/pypi.yml
Labels: enhancement

#30 OPENAI_BASE_URL env var support
  docker-compose.yml
  minitap/mobile_use/config.py
  minitap/mobile_use/services/llm.py
Labels: enhancement

#33 feat: fix maestro studio health check state between restarts
  minitap/mobile_use/sdk/agent.py
  minitap/mobile_use/servers/stop_servers.py
Labels: bug

#38 cortex: add support for multi-subgoal solving
  minitap/mobile_use/agents/cortex/cortex.md
  minitap/mobile_use/agents/cortex/cortex.py
  minitap/mobile_use/agents/cortex/types.py
  minitap/mobile_use/agents/executor/executor.py
  minitap/mobile_use/agents/orchestrator/human.md
  minitap/mobile_use/agents/orchestrator/orchestrator.md
  minitap/mobile_use/agents/orchestrator/orchestrator.py
  minitap/mobile_use/agents/orchestrator/types.py
  minitap/mobile_use/agents/planner/planner.md
  minitap/mobile_use/agents/planner/planner.py
  minitap/mobile_use/agents/planner/types.py
  minitap/mobile_use/agents/planner/utils.py
  minitap/mobile_use/controllers/mobile_command_controller.py
  minitap/mobile_use/graph/graph.py
  minitap/mobile_use/graph/state.py
  minitap/mobile_use/sdk/agent.py
  minitap/mobile_use/tools/mobile/back.py
  minitap/mobile_use/tools/mobile/copy_text_from.py
  minitap/mobile_use/tools/mobile/erase_text.py
  minitap/mobile_use/tools/mobile/find_packages.py
  minitap/mobile_use/tools/mobile/input_text.py
  minitap/mobile_use/tools/mobile/launch_app.py
  minitap/mobile_use/tools/mobile/long_press_on.py
  minitap/mobile_use/tools/mobile/open_link.py
  minitap/mobile_use/tools/mobile/paste_text.py
  minitap/mobile_use/tools/mobile/press_key.py
  minitap/mobile_use/tools/mobile/stop_app.py
  minitap/mobile_use/tools/mobile/swipe.py
  minitap/mobile_use/tools/mobile/take_screenshot.py
  minitap/mobile_use/tools/mobile/tap.py
  minitap/mobile_use/tools/mobile/wait_for_animation_to_end.py
Labels: enhancement
